[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GEMINI_API_KEY = ""

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 